#!/bin/bash
# vim ft=sh

usage() {
cat << EOF

Usage: bookmarkletify <FILE>

  Convert JavaScript files to bookmarklets

Example:
  $ bookmarkletify script.js

Via stdin:
  $ cat script.js | bookmarkletify

Options:
  -h --help                Display software usage
EOF
}

if [[ $@ == "-h" || $@ == "--help" ]]; then
  usage
  exit 0
fi

has_node=`which node`

bookmarkletify() {
  local script=$1

  if [ -z $has_node ]; then
    echo -e "Haven't found Node.js binary\n\n  $ brew install node"
    exit 1
  fi

  if [ -t 0 ]; then
    if [ -z $@  ]; then
      usage
      exit
    fi

    local minified=`npx uglify-js $script`
  else
    local minified=`npx uglify-js`
  fi

  local encoded=`node -p "encodeURIComponent('$minified')"`
  local bookmarklet="javascript:(function(){;$encoded;})()"

  echo -n $bookmarklet
}

bookmarkletify $@
